version: '3.1'

networks:
    postgresnet:

services:
  postgresql:
    image: postgres
    hostname: localhost
    container_name: postgresql
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=mydatabase
    networks:
      - postgresnet

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - postgresnet

  app:
    build: .
    hostname: app
    container_name: app
    volumes:
      - ./app:/app
    command: "pip install -r requirements.txt"
    depends_on:
      - postgresql
    networks:
      - postgresnet
